version: '3'

services:
  config-service:
    build: ./config-service
    ports:
      - ${CONFIG_SERVICE_PORT}:${CONFIG_SERVICE_PORT}
    depends_on:
      - rabbit-mq
    restart: always

  eureka-service:
    build: ./eureka-service
    ports:
      - ${EUREKA_SERVICE_PORT}:${EUREKA_SERVICE_PORT}
    depends_on:
      - rabbit-mq
      - config-service
    restart: always

  gateway-service:
    build: ./gateway-service
    ports:
      - ${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}
    depends_on:
      - rabbit-mq
      - config-service
    restart: always

  auth-service:
    build: ./auth-service
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    depends_on:
      - mysql
      - rabbit-mq
      - config-service
    restart: always

  plan-service:
    build: ./plan-service
    ports:
      - ${PLAN_SERVICE_PORT}:${PLAN_SERVICE_PORT}
    depends_on:
      - mysql
      - rabbit-mq
      - config-service
    restart: always

  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_SUB_PORT}:${RABBITMQ_SUB_PORT}

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
