spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Side-Project-Planting/Environment.git
          search-paths: property
          private-key-file: ~/.ssh/id_ed25519
  application:
    name: config-service
  profiles:
    active: ${profileLevel}
