name: Backend CI
on:
  pull_request:
    branches: [dev, main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 복제
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Gradle 권한 추가
        run: chmod +x ./gradlew

      - name: 캐싱
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-



      - name: 자바 17 버전 지정
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: 린트 검사
        run: ./gradlew checkstyleMain --console=plain --no-daemon

      - name: 테스트 실행
        run: ./gradlew test

      - name: 빌드 확인
        run: ./gradlew build -x test
